(() => {
  const { cx, cy } = window.KB;
  const S = {
    version: '6.9-permanent-towers',
    speed: 1,
    started: false,
    paused: false,
    gameOver: false,
    restarts: 2,
    waveSnapshot: null,
    lives: 15,
    gold: 180,
    wave: 0,
    score: 0,
    phase: 'build',
    waveStats: null,
    runStats: { heroKills: 0, towerKills: 0, otherKills: 0, leaked: 0, powerups: 0, goldEarned: 0, bonusGold: 0, interestGold: 0, wavesCleared: 0 },
    selected: null,
    sel: null,
    menuOpen: true,
    aiEngineerOwned: false,
    placeDir: 1,
    devToolsOpen: false,
    devUnlimitedGold: false,
    devInvincible: false,
    devShowInfo: false,
    devArenaChoice: 'field',
    weapon: 'blunderbuss',
    loadout: [],
    towers: [], barriers: [], barrels: [], enemies: [], shots: [], heroShots: [], enemyShots: [],
    parts: [], texts: [], oilPatches: [], firePatches: [], healthOrbs: [], queue: [],
    timer: 0, spawnCount: 0,
    waveActive: false,
    bossActive: false,
    bossSpawned: false,
    bossIntro: 0,
    bossAppearance: 0,
    clearFlash: 0,
    path: [],
    paths: [],
    levelId: 'field',
    levelLabel: 'Field',
    mutationPending: false,
    pendingUpgrade: false,
    gameState: 'betweenWaves',
    mutationWaveType: 'hero',
    heroMutations: [],
    trapMutations: [],
    pendingMutationChoices: [],
    waveBanner: '',
    waveBannerKind: '',
    waveBannerTime: 0,
    waveBannerKey: '',
    spawningActors: [],
    shakeTime: 0,
    shakeAmt: 0,
    slimeKingAppearances: 0,
    hero: {
      x: cx(2),
      y: cy(13),
      hp: 100,
      max: 100,
      level: 1,
      cool: 0,
      inv: 0,
      shoveCd: 0,
      weapon: 'blunderbuss',
      weaponCd: 0,
      secondaryCd: 0,
      charge: 0,
      charging: false,
      weaponRecoil: 0,
      spawnState: 'active',
      spawnLock: 0,
      flaskCharges: 0,
      shieldHits: 0,
      blunderShieldUntil: 0,
      blunderShieldMult: 1,
      upgrades: [],
      upgradeChoices: [],
      upgradeLevel: 0,
      fireRateMult: 1,
      damageMult: 1,
      shoveForceMult: 1,
      critChance: 0,
      pierceCount: 0,
      freezeDurationMult: 1,
      freezeTrapVuln: 0,
      chainBonus: 0,
      stormChainBonus: 0,
      stormStunMult: 1,
      crossbowStunMult: 1,
      crossbowKnockbackMult: 1,
      blunderDamageMult: 1,
      goldMult: 1,
      trapCooldownMult: 1,
      trinketAttackSlow: 0,
      trinketFireRateMult: 1,
      trinketMoveMult: 1,
      trinketFireRateActiveMult: 1,
      trinketMoveActiveMult: 1,
      trinketGoldActiveMult: 1,
      overclockAura: false,
      lastStandBeacon: false,
      lastStandBeaconActive: false,
    },
    engineer: { active: false, x: cx(3), y: cy(13), hp: 90, max: 90, cool: 0, inv: 0, dash: 0, dashCd: 0, aimX: cx(8), aimY: cy(8), volleyCd: 0, oilCd: 0, shoveCd: 0 },
    net: { mode: 'solo', pc: null, dc: null, connected: false, remoteInput: { up:false, down:false, left:false, right:false, shoot:false, volley:false, oil:false, aimX:0, aimY:0 }, remotePrev: { volley:false, oil:false }, lastSend: 0, lastSnapshot: 0 },
    mods: { gold: 1.14, dmg: 1, overclockUntil: 0, frenzyUntil: 0, hasteUntil: 0, coinPurseUntil: 0, lastStandUntil: 0, riftShieldUntil: 0 },
  };
  window.S = S;
})();
